<?
$PERM["ws_updatecomplaints.php"]["10"]="R";
$PERM["ws_updatecomplaints.php"]["*"]="R";
$PERM["cron"]["*"]="D";
$PERM["auth"]["*"]="D";
$PERM["load-test"]["2"]="D";
$PERM["load-test"]["5"]="D";
$PERM["load-test"]["3"]="D";
$PERM["load-test"]["4"]="D";
$PERM["load-test"]["6"]="D";
$PERM["load-test"]["7"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["load-catalog"]["*"]="D";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>