<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Личный кабинет физ. лица");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:desktop", 
	"sotbit_cabinet", 
	array(
		"COMPONENT_TEMPLATE" => "sotbit_cabinet",
		"ID" => "holder1s1",
		"CAN_EDIT" => "N",
		"COLUMNS" => "3",
		"GADGETS" => array(
			0 => "ALL",
		),
		"G_RSSREADER_CACHE_TIME" => "3600",
		"G_RSSREADER_SHOW_URL" => "N",
		"G_RSSREADER_PREDEFINED_RSS" => "",
		"GU_RSSREADER_TITLE_STD" => "",
		"GU_RSSREADER_CNT" => "10",
		"GU_RSSREADER_RSS_URL" => "",
		"GU_RSSREADER_IS_HTML" => "N",
		"G_BLANK_PATH_TO_BLANK" => "/personal/blank_zakaza/",
		"G_BLANK_INIT_JQUERY" => "N",
		"GU_BLANK_TITLE_STD" => "",
		"GU_HTML_AREA_TITLE_STD" => "",
		"GU_FAVORITES_TITLE_STD" => "",
		"G_ACCOUNTPAY_PATH_TO_BASKET" => "/personal/cart/",
		"G_ACCOUNTPAY_PATH_TO_PAYMENT" => "/personal/order/payment",
		"G_ACCOUNTPAY_PERSON_TYPE_ID" => "2",
		"GU_ACCOUNTPAY_TITLE_STD" => "",
		"G_REVIEWS_MAX_RATING" => "5",
		"G_REVIEWS_PATH_TO_REVIEWS" => "/personal/reviews/",
		"GU_REVIEWS_TITLE_STD" => "",
		"GU_REVIEWS_CNT" => "1",
		"GU_REVIEWS_TYPE" => "ALL",
		"G_BASKET_PATH_TO_BASKET" => "/personal/cart/",
		"GU_BASKET_TITLE_STD" => "",
		"G_BUYERS_PATH_TO_BUYER_DETAIL" => "/personal/profile/buyer/?id=#ID#",
		"GU_BUYERS_TITLE_STD" => "",
		"G_DELAYBASKET_PATH_TO_BASKET" => "/personal/cart/?delay=1",
		"GU_DELAYBASKET_TITLE_STD" => "",
		"G_PROFILE_PATH_TO_PROFILE" => "/personal/profile/",
		"GU_PROFILE_TITLE_STD" => "",
		"G_SUBSCRIBE_PATH_TO_SUBSCRIBES" => "/personal/subcribe/",
		"GU_SUBSCRIBE_TITLE_STD" => "",
		"G_PROBKI_CACHE_TIME" => "3600",
		"G_PROBKI_SHOW_URL" => "N",
		"GU_PROBKI_TITLE_STD" => "",
		"GU_PROBKI_CITY" => "c213",
		"G_WEATHER_CACHE_TIME" => "3600",
		"G_WEATHER_SHOW_URL" => "N",
		"GU_WEATHER_TITLE_STD" => "",
		"GU_WEATHER_COUNTRY" => "Россия",
		"GU_WEATHER_CITY" => "c213",
		"G_DISCOUNT_ID_DISCOUNT" => "1",
		"G_DISCOUNT_PATH_TO_PAGE" => "",
		"GU_DISCOUNT_TITLE_STD" => "",
		"G_ORDERS_PATH_TO_ORDERS" => "/personal/order/",
		"G_ORDERS_PATH_TO_ORDER_DETAIL" => "/personal/order/detail/#ID#/",
		"GU_ORDERS_TITLE_STD" => "",
		"GU_ORDERS_STATUS" => "ALL",
		"GU_ORDERS_LIMIT" => "2",
		"G_BUYORDER_PATH_TO_ORDER_DETAIL" => "/personal/order/detail/#ID#/",
		"G_BUYORDER_PATH_TO_PAY" => "/personal/order/payment/",
		"G_BUYORDER_ORG_PROP" => array(
		),
		"GU_BUYORDER_TITLE_STD" => ""
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>